// <auto-generated />
namespace Contoso2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InstructorAdded3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InstructorAdded3));
        
        string IMigrationMetadata.Id
        {
            get { return "201712160650528_InstructorAdded3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
